name: Continuous Integration

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: actions/checkout@v4

      - name: Run unit tests
        run: go test ./...

